# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js

node_js:
  - 6.9

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master
    - feature*

# using pre-defined build variables
# full list http://docs.shippable.com/ci/advancedOptions/environmentVariables/
env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/

build:
  ci:
    # npm mirrors can sometimes be flaky, better to use shippable_retry
    # http://docs.shippable.com/ci/advancedOptions/retry/
    - shippable_retry npm install
    - node $SHIPPABLE_BUILD_DIR/example.js

  post_ci:
    - echo "finished build"

  on_success:
    - echo "successfully built app"

# Integrations are used to connect external resources to CI
# http://docs.shippable.com/integrations/overview/
integrations:
  # http://docs.shippable.com/ci/shippableyml/#notifications
  notifications:
    # turns off email for PR builds, notifies only on failure or change in status
    # http://docs.shippable.com/integrations/notifications/email/
    - integrationName: email
      type: email
      on_success: change
      on_failure: always
      on_pull_request: never

resources:
  # References Subscription Integration pointing to Key-Value Account Integration # holding Shippable API Token 
  # Create Shippable API Token: 
  #   http://docs.shippable.com/platform/management/account/api-tokens
  # Create Key-Value Account Integration to hold API Token: 
  #   http://docs.shippable.com/platform/integration/key-value
  # Integration resource: 
  #   http://docs.shippable.com/platform/workflow/resource/integration
  - name: shippable-api-token
    type: integration
    integration: ttrahan-api-token

  # Resource to store values output from 'module' runCI job
  # Params resource: 
  #   http://docs.shippable.com/platform/workflow/resource/params
  - name: npm-module-params
    type: params
    version:
      params:
        MODULE_VERSION: "seed"
        MODULE_BRANCH: "seed"
        TRIGGER_BRANCH: "seed"

jobs:
  # CI job for 'module' (CI config in node-dependency-sample-module repo)
  - name: node-dependency-sample-module_runCI
    type: runCI
    steps:
      - OUT: npm-module-params

  # Job to trigger 'app' build via Shippable API
  - name: npm-module-api-trigger
    type: runSh
    steps:
      # this will inject the variable values output from 'module' CI job
      - IN: npm-module-params
      # this will inject the APITOKEN key value from the Subscription Integration
      - IN: shippable-api-token
      - TASK:
        # env var APITOKEN comes from the shippable-api-token input
        - script: 'curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" --header "Authorization: apiToken ${APITOKEN}" "https://api.shippable.com/projects/5a2709544cb6bc0700f012e0/newBuild?branch=${TRIGGER_BRANCH}"'

  # CI job for 'app' (CI config above)
  - name: node-dependency-sample-app_runCI
    type: runCI
    steps:
      - IN: npm-module-api-trigger
        switch: off

