# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js

node_js:
  - 6.9

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master
    - feature*

# using pre-defined build variables
# full list http://docs.shippable.com/ci/advancedOptions/environmentVariables/
env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/

build:
  ci:
    # npm mirrors can sometimes be flaky, better to use shippable_retry
    # http://docs.shippable.com/ci/advancedOptions/retry/
    - shippable_retry npm install
    - node $SHIPPABLE_BUILD_DIR/example.js

  post_ci:
    - echo "finished build"

  on_success:
    - echo "successfully built app"

# Integrations are used to connect external resources to CI
# http://docs.shippable.com/integrations/overview/
integrations:
  # http://docs.shippable.com/ci/shippableyml/#notifications
  notifications:
    # turns off email for PR builds, notifies only on failure or change in status
    # http://docs.shippable.com/integrations/notifications/email/
    - integrationName: email
      type: email
      on_success: change
      on_failure: always
      on_pull_request: never

resources:
  - name: npm-module-trigger
    type: trigger
    version:
      counter: module.master.1 

  - name: shippable-api-token
    type: integration
    integration: ttrahan-api-token

  - name: npm-module-params
    type: params
    version:
      params:
        MODULE_VERSION: "seed"
        MODULE_BRANCH: "seed"
        TRIGGER_BRANCH: "seed"

jobs:
  - name: node-dependency-sample-module_runCI
    type: runCI
    steps:
      - OUT: npm-module-params

  - name: npm-module-api-trigger
    type: runSh
    steps:
      - IN: npm-module-params
      - IN: shippable-api-token
      - TASK:
        - script: echo ${SHIPPABLEAPITOKEN_PATH}
        - script: echo ${SHIPPABLEAPITOKEN_NAME}
        - script: echo ${SHIPPABLEAPITOKEN_INTEGRATION_APITOKEN}
        - script: echo ${#SHIPPABLEAPITOKEN_APITOKEN}
        - script: printenv | grep APITOKEN
        - script: "curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: apiToken $SHIPPABLEAPITOKEN_APITOKEN' -d '{\"branchName\": \"$TRIGGER_BRANCH\"}' 'https://api.shippable.com/projects/5a2709544cb6bc0700f012e0/newBuild'"

  - name: node-dependency-sample-app_runCI
    type: runCI
    steps:
      - IN: npm-module-api-trigger

